"""Type definitions for Chat and Message Completions."""

from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field


class FunctionDefinition(BaseModel):
    """Specification of a function that can be called by the model."""

    name: str = Field(..., description="The name of the function to call")
    description: Optional[str] = Field(None, description="A description of what the function does")
    parameters: Optional[Dict[str, Any]] = Field(None, description="JSON schema defining function parameters")


class Tool(BaseModel):
    """Tool definition provided to the model."""

    type: str = Field("function", description="The type of the tool")
    function: FunctionDefinition = Field(..., description="Function specifications")


class FunctionCall(BaseModel):
    """The function call generated by the model."""

    name: str = Field(..., description="Name of the function to call")
    arguments: str = Field(..., description="Arguments JSON string")


class ToolCall(BaseModel):
    """A tool call invoked by the model."""

    id: Optional[str] = Field(None, description="Unique tool call ID")
    type: str = Field("function", description="The type of the tool call")
    function: FunctionCall = Field(..., description="Function to call")


class ChatMessage(BaseModel):
    """A message in a chat conversation."""

    role: str = Field(..., description="Role of the message sender (system, user, assistant, tool)")
    content: Optional[str] = Field(None, description="Content of the message")
    name: Optional[str] = Field(None, description="Optional name of the participant")
    tool_calls: Optional[List[ToolCall]] = Field(None, description="Tool calls generated by assistant")
    tool_call_id: Optional[str] = Field(None, description="Tool call ID for tool role message response")


class Usage(BaseModel):
    """Token usage details."""

    prompt_tokens: int = Field(0, description="Tokens used in the prompt")
    completion_tokens: int = Field(0, description="Tokens generated in the completion")
    total_tokens: int = Field(0, description="Total tokens consumed")


class ChatCompletionChoice(BaseModel):
    """A single chat completion choice."""

    index: int = Field(0, description="Index of the choice")
    message: ChatMessage = Field(..., description="The generated message")
    finish_reason: Optional[str] = Field(None, description="Reason why generation stopped (stop, tool_calls, length)")


class ChatCompletion(BaseModel):
    """Response returned for a non-streaming chat completion."""

    id: str = Field(..., description="Unique completion ID")
    object: str = Field("chat.completion", description="Object type")
    created: int = Field(..., description="Unix timestamp of creation")
    model: str = Field(..., description="Model used for generation")
    choices: List[ChatCompletionChoice] = Field(default_factory=list, description="List of completion choices")
    usage: Optional[Usage] = Field(None, description="Token usage statistics")

    @property
    def content(self) -> str:
        """Helper property to access first choice message content directly (Anthropic-style)."""
        if self.choices and self.choices[0].message.content:
            return self.choices[0].message.content
        return ""


class ChatCompletionChunkDelta(BaseModel):
    """Delta update in a streaming chunk."""

    role: Optional[str] = Field(None, description="Role update")
    content: Optional[str] = Field(None, description="Streamed text token/delta")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Partial tool calls")


class ChatCompletionChunkChoice(BaseModel):
    """Choice representation in a stream chunk."""

    index: int = Field(0, description="Index of the choice")
    delta: ChatCompletionChunkDelta = Field(default_factory=ChatCompletionChunkDelta, description="Content delta")
    finish_reason: Optional[str] = Field(None, description="Finish reason if generation ended")


class ChatCompletionChunk(BaseModel):
    """A single chunk emitted during streaming chat completion."""

    id: str = Field(..., description="Completion ID")
    object: str = Field("chat.completion.chunk", description="Object type")
    created: int = Field(..., description="Unix timestamp")
    model: str = Field(..., description="Model name")
    choices: List[ChatCompletionChunkChoice] = Field(default_factory=list, description="List of chunk choices")
